# SPDX-FileCopyrightText: The terraform-provider-migadu Authors
# SPDX-License-Identifier: 0BSD

FROM docker.io/metio/devcontainers-go:latest

RUN go install github.com/hashicorp/terraform@main
RUN go install gotest.tools/gotestsum@latest
RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@master
