GET https://api.migadu.com/v1/domains/{{DOMAIN}}/mailboxes
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}
Content-Type: application/json

###

GET https://api.migadu.com/v1/domains/{{DOMAIN}}/mailboxes/test
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}
Content-Type: application/json

###

POST https://api.migadu.com/v1/domains/{{DOMAIN}}/mailboxes
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}
Content-Type: application/json

{
  "name": "Some Name",
  "local_part": "test",
  "password": "Sup3r_s3cr3T",
  "recipient_denylist": ["abuse@{{DOMAIN}}"]
}

###

PUT https://api.migadu.com/v1/domains/{{DOMAIN}}/mailboxes/test
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}
Content-Type: application/json

{
  "name": "Some New Name"
}

###

DELETE https://api.migadu.com/v1/domains/{{DOMAIN}}/mailboxes/test
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}
Content-Type: application/json
