GET https://api.migadu.com/v1/domains/xn--ho-hia.de/mailboxes
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}

###

GET https://api.migadu.com/v1/domains/xn--ho-hia.de/mailboxes/seb
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}

###

GET https://api.migadu.com/v1/domains/xn--ho-hia.de/mailboxes/seb/identities
Authorization: Basic {{MIGADU_USERNAME}} {{MIGADU_API_KEY}}
